Added Lodestar integration
dappnode/DAppNodePackage-web3signer pull request #10
Opened 2022-09-16 09:26 UTC by Nabsku

I have tested Lodestar on DAppNode with this [PR](https://github.com/dappnode/DAppNodePackage-Lodestar/pull/5). 

We will need to wait for Lodestar to include this in a stable release, as the fix for web3signer is currently only in the unstable branch.

2022-09-19 10:36 UTC, pablomendezroyo commented
looks good, however we should follow the flow **prater > gnosis chain > mainnet**

2023-02-15 08:45 UTC, pablomendezroyo commented
Status of this PR?

Seems to be a duplicate of https://github.com/dappnode/DAppNodePackage-web3signer/pull/9 which one has priority?

2023-02-27 13:24 UTC, nflaig requested changes

2023-02-27 13:24 UTC, nflaig commented on web3signer/security/lodestar/api-token.txt
> +api-token-0x8107edae469565b8cc7cd08addc2bd9a73cd9cfe8127e652caa4c7b5ad50a4bd
the api-token does not match the value of [DAppNodePackage-Lodestar api-token.txt](https://github.com/dappnode/DAppNodePackage-Lodestar/blob/main/validator/security/api-token.txt), I would suggest we align the api-token to be the same for all packages as it is done for other CLs. Related PR https://github.com/dappnode/DAppNodePackage-Lodestar/pull/36 and https://github.com/dappnode/StakingBrain/pull/196

```suggestion
api-token-0x7fd16fff6453982a5d8bf14617e7823b68cd18ade59985befe64e0a659300e7d
```

2023-02-28 13:36 UTC, closed without merging