Show new UI in Web3Signer package
dappnode/DAppNodePackage-web3signer pull request #18
Opened 2022-11-08 23:56 UTC by dsimog01

Shown new UI in web3signer

2022-11-09 08:09 UTC, pablomendezroyo requested changes

2022-11-09 08:09 UTC, pablomendezroyo commented on dappnode_package.json
>      "eduadiez <eduadiez@gmail.com> (https://github.com/eduadiez)"
missing comma

2022-11-09 08:09 UTC, pablomendezroyo commented on dappnode_package.json
> +      "envs": ["CONSENSUS_CLIENT_PRATER", "EXECUTION_CLIENT_PRATER"],
It should be `CONSENSUS_CLIENT_MAINNET` instead of `CONSENSUS_CLIENT_PRATER`

2022-11-09 08:09 UTC, pablomendezroyo commented on dappnode_package.json
> +    { "envs": ["CONSENSUS_CLIENT_PRATER"], "services": ["web3signer"] }
same as above

2022-11-09 08:09 UTC, pablomendezroyo commented on ui/.env
> +CONSENSUS_CLIENT=$_DAPPNODE_GLOBAL_CONSENSUS_CLIENT
missing `MAINNET`

2022-11-10 16:58 UTC, dsimog01 commented
After fix, the package has been built and can be installed with this IPFS hash: /ipfs/QmS2u1Azk2hFuSJoN3sEDL3oo339jz3MtbgiaVnhVhnkeC

2022-11-15 11:13 UTC, pablomendezroyo approved these changes

2022-11-15 11:16 UTC, merged